# Generated by Django 3.0.3 on 2020-11-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('from_mail', models.EmailField(max_length=254)),
                ('to_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
