# Generated by Django 3.0.3 on 2020-11-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='from_mail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mailmodel',
            name='to_mail',
            field=models.CharField(max_length=255),
        ),
    ]
