# Generated by Django 3.0.3 on 2020-11-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_mymodel_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='no_tel',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
