# Generated by Django 3.0.3 on 2020-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_auto_20201103_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='sex',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
