# Generated by Django 3.0.3 on 2020-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_mymodel_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
