version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  db:
    image: postgres:10.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=first_site
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
